import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils"
import { ThemeProvider } from "@/components/providers/theme-provider";
import Authlayout from "./(auth)/(routes)/layout";
import {
  ClerkProvider
} from '@clerk/nextjs'
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Light's Discord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(`${dosis.variable} ${dosis.variable} antialiased`,
          "bg-white dark:bg-[#313338]"
        )}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}